apiVersion: batch/v1
kind: CronJob
metadata:
  name: gpu-node-manager
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gpu-node-manager
              image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
              imagePullPolicy: Always
              env:
                - name: GPU_NODE_NAME
                  value: {{ .Values.gpuNodeName | default "gpu-node-manager" }}
                - name: WAKE_ENDPOINT
                  value: {{ .Values.wakeEndpoint | default "http://gpu-api.homelab/wake" }}
                - name: SHUTDOWN_ENDPOINT
                  value: {{ .Values.shutdownEndpoint | default "http://gpu-api.homelab/shutdown" }}
                - name: KUBERNETES_SERVICE_HOST
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: KUBERNETES_SERVICE_PORT
                    value: {{ .Values.kubernetesServicePort | default "443" }}
          serviceAccountName: gpu-node-manager
          restartPolicy: OnFailure
