apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-node-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-node-manager
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-node-manager
subjects:
  - kind: ServiceAccount
    name: gpu-node-manager
roleRef:
  kind: ClusterRole
  name: gpu-node-manager
  apiGroup: rbac.authorization.k8s.io
