image:
  repository: ghcr.io/dseif0x/k8s-gpu-autoprovision
  tag: latest

nodeGroups:
  - name: foo1
    gpuCount: 1
    scaleUpEndpoint: http://node-foo/up
    scaleDownEndpoint: http://node-foo/down